AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket for hosting a static resume website

Parameters:
  BucketName:
    Type: String
    Description: Unique name for the S3 bucket
    Default: resume-site-2025
    ConstraintDescription: Must be a unique S3 bucket name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Project
          Value: ResumeWebsite

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

Outputs:
  WebsiteURL:
    Description: URL for the S3 static website
    Value: !GetAtt S3Bucket.WebsiteURL
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref BucketName