name: Deploy CloudFormation Stack

on:
  push:
    branches: [main]  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yml \
            --stack-name resume-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides PrivateBucketName=ching-resume-html PublicBucketName=ching-resume-auth-page PreSignedURLExpiration=3600 DomainName=resume.ching.dev

